version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - TMS_network
  
  mongodb-container:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
    networks:
        - TMS_network
  
  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - 6379:6379
    volumes:
      - redisData:/data
    networks:
      - TMS_network
    


networks:
  TMS_network:
  
volumes:
  mongoData:
  redisData:
  


